import {useRouter} from "next/router";
import {HistoryItem} from "@/hooks/useHldGenerator";
import {RequirementsForm} from "@/components/input/RequirementsForm";
import dynamic from "next/dynamic";
import React from "react";
import Head from "next/head";
import {Grid} from "@mui/material";
import {Loading} from "@/components/history/Loading";

const SystemDisplay = dynamic(import("@/components/graph/SystemDisplay"), {ssr: false});


const SystemHistory = () => {
  const router = useRouter()
  const {historyID} = router.query
  const [history, setHistory] = React.useState<HistoryItem>()
  React.useEffect(() => {
    const loadedHistory = JSON.parse(localStorage?.getItem("history") || "[]")
    const historyItem = loadedHistory.find((item: HistoryItem) => item.id === historyID)
    setHistory(historyItem)
  }, [historyID, setHistory]);

  return <>
    <Head>
      <title>HLD Copilot</title>
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    <Grid container={true}>
      {history ? <>
        <Grid item={true} xs={12} md={4}>
          <RequirementsForm
            _projectTitle={history.title}
            _projectDescription={history.description}
            _requirements={history.requirements}
            _projectID={history.id}
          />
        </Grid>
        <Grid item={true} xs={12} md={8}>
          <SystemDisplay system={history.system}/>
        </Grid>
      </> : <Loading/>}
    </Grid>
  </>
}

export default SystemHistory