import {useRouter} from "next/router";
import {HistoryItem} from "@/hooks/useHldGenerator";
import {RequirementsForm} from "@/components/input/RequirementsForm";
import {Stack} from "@mui/system";
import dynamic from "next/dynamic";
import React from "react";
import Head from "next/head";
import {Container} from "@mui/material";

const SystemDisplay = dynamic(import("@/components/graph/SystemDisplay"), {ssr: false});

const SystemHistory = () => {
  const router = useRouter()
  const {historyID} = router.query
  const [history, setHistory] = React.useState<HistoryItem>()
  React.useEffect(() => {
    const loadedHistory = JSON.parse(localStorage?.getItem("history") || "[]")
    const historyItem = loadedHistory.find((item: HistoryItem) => item.id === historyID)
    setHistory(historyItem)
  }, [historyID, setHistory]);

  return <>
    <Head>
      <title>HLD Copilot</title>
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    <Container maxWidth={false} sx={{
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-around",
        alignItems: "center",
    }}>
      {history ? <> <RequirementsForm
        _projectTitle={history.title}
        _projectDescription={history.description}
        _requirements={history.requirements}
        _projectID={history.id}
      />
        <SystemDisplay system={history.system}/></>: <p>Loading...</p>}
    </Container></>
}

export default SystemHistory