import Head from 'next/head'
import {Inter} from 'next/font/google'
import {RequirementsForm} from "@/components/input/RequirementsForm";
import {Stack} from "@mui/system";
import {History} from "@/components/history/History";

const inter = Inter({subsets: ['latin']})

export default function Home() {
  return (
    <>
      <Head>
        <title>HLD Copilot</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
        <Stack spacing={2} direction={"row"}>
          <RequirementsForm/>
          <History/>
        </Stack>
    </>
  )
}
