import Head from 'next/head'
import {Inter} from 'next/font/google'
import {RequirementsForm} from "@/components/input/RequirementsForm";
import {Stack} from "@mui/system";
import {History} from "@/components/history/History";
import {Container, Grid} from "@mui/material";

const inter = Inter({subsets: ['latin']})

export default function Home() {
  return (
    <>
      <Head>
        <title>HLD Copilot</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Grid container={true}>
        <Grid item={true} xs={12} md={4}>
          <RequirementsForm/>
        </Grid>
        <Grid item={true} xs={12} md={8}>
          <History/>
        </Grid>
      </Grid>
    </>
  )
}
